import fs from 'node:fs';
import path from 'node:path';
import { BootResult } from './result.js';
import KeyManager from '../../config/KeyManager.js';

/**
 * EnvironmentDetector — Detection and validation of environment configuration.
 *
 * SRP: only concerns environment variables and the .env file.
 *  - Detects if .env exists and creates it from env_example if needed.
 *  - Validates critical variables according to the boot mode.
 *  - Reports each problem with its exact solution.
 */

const REQUIRED_FOR_LTI = [
  { key: 'CANVAS_BASE_URL', desc: 'Canvas LMS base URL' },
  { key: 'LTI_CLIENT_ID', desc: 'LTI tool Client ID' },
  { key: 'GEMINI_API_KEY', desc: 'Gemini AI API Key' },
];



export class EnvironmentDetector {
  constructor(pluginDir) {
    this.pluginDir = pluginDir;
    this.envPath = path.resolve(pluginDir, '.env');
    this.examplePath = path.resolve(pluginDir, '.env.example');
  }

  /** Reads .env manually (without dotenv) for audit. */
  readRawEnv() {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    if (!fs.existsSync(this.envPath)) return {};
    const out = {};
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    for (const line of fs.readFileSync(this.envPath, 'utf8').split('\n')) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      const idx = t.indexOf('=');
      if (idx > 0) out[t.slice(0, idx)] = t.slice(idx + 1).trim();
    }
    return out;
  }

  /** Ensures .env exists from .env.example or a native fallback. Returns BootResult. */
  ensureEnvFile(log) {
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    if (fs.existsSync(this.envPath)) {
      log.success('File .env present.');
      return BootResult.ok({ present: true });
    }
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    if (fs.existsSync(this.examplePath)) {
      fs.copyFileSync(this.examplePath, this.envPath);
      log.auto('.env created from .env.example.');
      return BootResult.fixed('.env file created from .env.example.');
    }
    
    // Absolute fallback: Create base memory file if nothing exists.
    const fallbackEnv = `# Plugin Feedback - Autogenerated\n
CANVAS_BASE_URL=https://localhost:8443
CANVAS_ISSUER=https://localhost:8443
CANVAS_ACCESS_TOKEN=
DB_HOST=127.0.0.1
DB_USER=postgres
DB_PASSWORD=CHANGE_ME_db_password_strong
DB_NAME=feedback_plugin_db
DB_PORT=5432
ENCRYPTION_KEY=
WEBHOOK_SECRET=
DEV_TOKEN_SECRET=
LTI_DEPLOYMENT_IDS=
GEMINI_API_KEY=YOUR_API_KEY_HERE
CANVAS_COURSE_ID=1
CANVAS_API_HOST=canvas.local
# semgrep-ignore
CANVAS_ADMIN_PASS=password123
# semgrep-ignore
CANVAS_TEACHER_PASS=password123
# semgrep-ignore
CANVAS_STUDENT_PASS=password123
LOCAL_DEV_PASSWORD_HASH=
LTI_CLIENT_ID=
LTI_CLIENT_SECRET=
USE_LOCAL_DATA=false
VITE_USE_LOCAL_DATA=false
`;
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    fs.writeFileSync(this.envPath, fallbackEnv, 'utf8');
    log.auto('.env created from security template (Memory fallback).');
    return BootResult.fixed('.env file created from native template.');
  }

  /** Validates critical variables according to the mode. */
  validate(log, mode) {
    KeyManager.ensureKeys(this.pluginDir, log);

    const env = { ...process.env, ...this.readRawEnv() };
    const missing = [];

    for (const { key, desc } of REQUIRED_FOR_LTI) {
      // eslint-disable-next-line security/detect-object-injection
      if (!env[key] || !env[key].trim()) {
        if (mode === '3' && key === 'LTI_CLIENT_ID') {
          log.info(`Missing variable: LTI_CLIENT_ID (Will be automatically generated and injected shortly)`);
        } else {
          missing.push(`${key} (${desc})`);
        }
      }
    }

    // STARTUP_MODE is defined by the orchestrator, but it is good to have it in .env
    // for reproducible non-interactive boots. Not critical if missing.
    if (mode === '2' && (!env.CANVAS_ACCESS_TOKEN || !env.CANVAS_ACCESS_TOKEN.trim())) {
      missing.push('CANVAS_ACCESS_TOKEN (required in API mode)');
    }

    if (missing.length) {
      for (const m of missing) log.warn(`Missing variable: ${m}`);
      return BootResult.fail(
        false,
        `${missing.length} missing environment variable(s)`,
        `Add to .env: ${missing.join(', ')}`
      );
    }
    log.success('Critical environment variables present.');
    return BootResult.ok();
  }

  /** Ensures boot control variables exist with sane defaults. */
  ensureStartupVars(mode) {
    const env = this.readRawEnv();
    const needed = {};
    if (env.STARTUP_MODE === undefined) needed.STARTUP_MODE = mode || '3';
    if (env.NON_INTERACTIVE === undefined) needed.NON_INTERACTIVE = 'false';
    if (env.USE_LOCAL_DATA === undefined) needed.USE_LOCAL_DATA = 'false';
    if (env.VITE_USE_LOCAL_DATA === undefined) needed.VITE_USE_LOCAL_DATA = 'false';
    
    if (mode === '3' && env.CANVAS_BASE_URL === undefined) {
      needed.CANVAS_BASE_URL = 'https://localhost:8443';
    }
    if (Object.keys(needed).length === 0) return false;

    // eslint-disable-next-line security/detect-non-literal-fs-filename
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    const lines = fs.existsSync(this.envPath) ? fs.readFileSync(this.envPath, 'utf8').split('\n') : [];
    for (const [k, v] of Object.entries(needed)) lines.push(`${k}=${v}`);
    // eslint-disable-next-line security/detect-non-literal-fs-filename
    fs.writeFileSync(this.envPath, lines.join('\n') + '\n', 'utf8');
    return true;
  }
}
