
services:
  db:
    container_name: feedback_plugin_db_local
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"

  gotenberg:
    container_name: feedback_plugin_gotenberg_local
    command: gotenberg --api-timeout=120s
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-I", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  app:
    container_name: feedback_plugin_app_local
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - GOTENBERG_URL=http://gotenberg:3000
    volumes:
      - ./apps/server:/app/apps/server
      - ./apps/client:/app/apps/client
      - ./packages:/app/packages
    command: npm run dev
